/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactLead = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdmin' : IDL.Func([], [IDL.Bool], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeadById' : IDL.Func([IDL.Nat], [IDL.Opt(ContactLead)], ['query']),
  'getLeadsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(ContactLead)], ['query']),
  'getLeadsInTimeRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(ContactLead)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactLead = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdmin' : IDL.Func([], [IDL.Bool], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeadById' : IDL.Func([IDL.Nat], [IDL.Opt(ContactLead)], ['query']),
    'getLeadsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(ContactLead)], ['query']),
    'getLeadsInTimeRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(ContactLead)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
